# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :take_screenshots do
  snapshot
end

lane :build_and_export do
  gym
  app_id = get_info_plist_value(
    path: "./CatsViewer/CatsViewer/GoogleService-Info.plist",
    key: "GOOGLE_APP_ID"
  )
  firebase_app_distribution(
    firebase_cli_token:ENV['1//0cQLzKR3xNUWXCgYIARAAGAwSNwF-L9IrC16gIDe5gxSipeDxhG2edG3Zj3cE1IpaptDUtdDCheUlQxxd2Va_XWCOSszSbH8isa8'],
    release_notes: "Some new project release",
    app: app_id
  )
end
 
